CREATE TABLE IF NOT EXISTS `employee_confiedential_documents` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `employee_id` INT NOT NULL,
    `uploaded_by` INT NOT NULL,
    `document_type_key` VARCHAR(120) NOT NULL,
    `document_type_label` VARCHAR(160) NOT NULL,
    `document_name` VARCHAR(255) NOT NULL,
    `document_date` DATE NOT NULL,
    `expiry_date` DATE NULL,
    `visibility_mode` ENUM('all', 'specific_users') NOT NULL DEFAULT 'all',
    `visibility_user_ids` TEXT NULL,
    `notes` TEXT NULL,
    `file_original_name` VARCHAR(255) NOT NULL,
    `file_stored_name` VARCHAR(255) NOT NULL,
    `file_path` VARCHAR(500) NOT NULL,
    `file_size` BIGINT UNSIGNED NOT NULL,
    `file_mime` VARCHAR(120) NOT NULL,
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deleted_at` DATETIME NULL,
    `deleted_by` INT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_emp_conf_docs_employee_id` (`employee_id`),
    KEY `idx_emp_conf_docs_uploaded_by` (`uploaded_by`),
    KEY `idx_emp_conf_docs_type_key` (`document_type_key`),
    KEY `idx_emp_conf_docs_is_deleted` (`is_deleted`),
    KEY `idx_emp_conf_docs_created_at` (`created_at`),
    CONSTRAINT `fk_emp_conf_docs_employee` FOREIGN KEY (`employee_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_emp_conf_docs_uploaded_by` FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_emp_conf_docs_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
