CREATE TABLE IF NOT EXISTS `attendance` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `punch_in` TIME DEFAULT NULL,
  `missing_punch_in_reason` TEXT DEFAULT NULL,
  `punch_out` TIME DEFAULT NULL,
  `missing_punch_out_reason` TEXT DEFAULT NULL,
  `approval_status` ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  `manager_id` INT(11) DEFAULT NULL,
  `approval_timestamp` DATETIME DEFAULT NULL,
  `manager_comments` TEXT DEFAULT NULL,
  `work_report` TEXT DEFAULT NULL,
  `overtime_status` ENUM('pending', 'approved', 'rejected', 'submitted', 'expired', 'resubmitted') DEFAULT 'pending',
  `Overtime_approval_status` ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  `overtime_approved_by` INT(11) DEFAULT NULL,
  `Manager_who_approved_rejected_overtime` INT(11) DEFAULT NULL,
  `overtime_actioned_at` DATETIME DEFAULT NULL,
  `auto_punch_out` TINYINT(1) DEFAULT 0,
  `location` VARCHAR(255) DEFAULT NULL,
  `within_geofence` TINYINT(1) DEFAULT NULL,
  `distance_from_geofence` FLOAT DEFAULT NULL,
  `geofence_id` INT(11) DEFAULT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `device_info` TEXT DEFAULT NULL,
  `image_data` LONGBLOB DEFAULT NULL,
  `latitude` DECIMAL(10, 8) DEFAULT NULL,
  `longitude` DECIMAL(11, 8) DEFAULT NULL,
  `accuracy` FLOAT DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `overtime` TIME DEFAULT NULL,
  `status` ENUM('present', 'absent', 'half_day', 'leave', 'holiday') DEFAULT 'present',
  `remarks` TEXT DEFAULT NULL,
  `modified_by` INT(11) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `working_hours` TIME DEFAULT NULL,
  `overtime_hours` TIME DEFAULT NULL,
  `shift_time` TIME DEFAULT NULL,
  `weekly_offs` VARCHAR(50) DEFAULT NULL,
  `is_weekly_off` TINYINT(1) DEFAULT 0,
  `punch_in_photo` VARCHAR(255) DEFAULT NULL,
  `punch_in_latitude` DECIMAL(10, 8) DEFAULT NULL,
  `punch_in_longitude` DECIMAL(11, 8) DEFAULT NULL,
  `punch_in_accuracy` FLOAT DEFAULT NULL,
  `punch_out_photo` VARCHAR(255) DEFAULT NULL,
  `punch_out_latitude` DECIMAL(10, 8) DEFAULT NULL,
  `punch_out_longitude` DECIMAL(11, 8) DEFAULT NULL,
  `punch_out_accuracy` FLOAT DEFAULT NULL,
  `shifts_id` INT(11) DEFAULT NULL,
  `punch_out_address` TEXT DEFAULT NULL,
  `overtime_reason` TEXT DEFAULT NULL,
  `punch_in_outside_reason` TEXT DEFAULT NULL,
  `punch_out_outside_reason` TEXT DEFAULT NULL,
  `missing_punch_in_id` INT(11) DEFAULT NULL,
  `missing_punch_out_id` INT(11) DEFAULT NULL,
  `missing_punch_reason` TEXT DEFAULT NULL,
  `missing_punch_approval_status` ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `manager_id` (`manager_id`),
  KEY `date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;