CREATE TABLE IF NOT EXISTS `overtime_requests` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `attendance_id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `shift_end_time` TIME NOT NULL,
  `punch_out_time` TIME NOT NULL,
  `overtime_hours` DECIMAL(5,2) NOT NULL,
  `work_report` TEXT DEFAULT NULL,
  `overtime_description` TEXT NOT NULL,
  `manager_id` INT(11) DEFAULT NULL,
  `status` ENUM('pending', 'approved', 'rejected', 'submitted', 'expired', 'resubmitted') DEFAULT 'pending',
  `resubmit_count` INT(11) DEFAULT 0,
  `submitted_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `actioned_at` TIMESTAMP NULL DEFAULT NULL,
  `manager_comments` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `attendance_id` (`attendance_id`),
  KEY `manager_id` (`manager_id`),
  KEY `date` (`date`),
  CONSTRAINT `fk_overtime_requests_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_overtime_requests_attendance` FOREIGN KEY (`attendance_id`) REFERENCES `attendance` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_overtime_requests_manager` FOREIGN KEY (`manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;